<html>

<head>
      <title>Renewable Energy system</title>
      <link href="style.css" rel="stylesheet"/>
	  <script type="text/javascript" src="jq/jq.js">
      </script>
      <script type="text/javascript" src="functions.js">
      </script>
</head>
  <body>
            <div id="wrap">
				<div id="head">
					<div id="header"><h1>Renewable Energy system</h1></div>
				</div>
	       <div id="mid">
            
           